### ISSUE TITLE
Pros and cons of Meteor-electron VS electrify 

### ISSUE THREAD

**Issue by gabrielstuff** [jrudio/meteor-electron#26]
Both package / app looks like providing the same functionality. 
Any difference in the philosophy or the development team behind ?

Project in question : https://github.com/arboleya/electrify

Thanks !

**Comment by jrudio** [comment]
Electrify is definitely better supported, mature, and I actually have it
listed as an alternative to this package in the README.

In terms of development difference, it looks like my package loads electron
when meteor starts up. I believe with electrify you need to run its
specific command when you want to run electron.

Not that big of a difference, but a difference.

A pro is that this package was the first meteor package that ran your
meteor app in electron. But that isn't much of a pro because not much has
been done to improve the development of desktop apps via this package.

All in all, if I were you, electrify is probably better.

**Comment by jrudio** [comment]
Going to close this if that somewhat helped you.
